!!python/object:src.exp.carlabev_hpc.ArgsCarlaBEV
anneal_lr: true
batch_size: 0
capture_video: true
clip_coef: 0.2
clip_coef_end: 0.05
clip_coef_start: 0.2
clip_vloss: true
cuda: true
decay_schedule: cosine
discrete: true
ent_coef: 0.005
ent_coef_end: 0.0005
ent_coef_start: 0.01
env_id: CarlaBEV-v0
exp_name: cnn-ppo-discrete-carlabev-12env-decay
gae_lambda: 0.97
gamma: 0.995
learning_rate: 0.0003
max_grad_norm: 0.5
minibatch_size: 0
norm_adv: true
num_envs: 12
num_iterations: 0
num_minibatches: 12
num_steps: 256
obs_space: bev
save_model: true
seed: 1
size: 128
target_kl: 0.01
torch_deterministic: true
total_timesteps: 30000000
update_epochs: 4
vf_coef: 0.7
vf_coef_end: 0.4
vf_coef_start: 0.7
